
- Modulo 2 : Estadistica y Visualizacion de Datos
- Sesion : 02
- Fecha : 08/11/2025
- Actualización : 02/05/2026

In [65]:
import pandas as pd
import numpy as np

In [66]:
listado_docentes = {
    "0001": {
        "nombres": "Ana Maria",
        "apellidos": "Lopez Garcia",
        "edad": 34
        },
    "0002": {
        "nombres": "Juan Carlos",
        "apellidos": "Perez Soto",
        "edad": 45
        },
    "0003": {
        "nombres": "Maria Elena",
        "apellidos": "Rodriguez Mendoza",
        "edad": 28
        }
    }

print(listado_docentes["0002"])
print(listado_docentes["0002"]["nombres"])

{'nombres': 'Juan Carlos', 'apellidos': 'Perez Soto', 'edad': 45}
Juan Carlos

### Pandas

-  Series
-  Dataframes

In [67]:
df = pd.DataFrame(listado_docentes)
print(df)

                   0001         0002               0003
nombres       Ana Maria  Juan Carlos        Maria Elena
apellidos  Lopez Garcia   Perez Soto  Rodriguez Mendoza
edad                 34           45                 28

In [68]:
df[["0001"]]

                   0001
nombres       Ana Maria
apellidos  Lopez Garcia
edad                 34

In [69]:
df["0001"]["nombres"]

'Ana Maria'

In [70]:
df.head()

                   0001         0002               0003
nombres       Ana Maria  Juan Carlos        Maria Elena
apellidos  Lopez Garcia   Perez Soto  Rodriguez Mendoza
edad                 34           45                 28

In [71]:
df["0004"] =  df["0001"]

In [72]:
df.head()

                   0001         0002               0003          0004
nombres       Ana Maria  Juan Carlos        Maria Elena     Ana Maria
apellidos  Lopez Garcia   Perez Soto  Rodriguez Mendoza  Lopez Garcia
edad                 34           45                 28            34

## Ejercicio

- Mostra la informacion de la edad del registro con ID = 0002
- Agregar un registro al dataframe , para tal fin duplicar el registro con ID = 0003

In [73]:
print(listado_docentes["0002"]["edad"])

df["0005"]=df["0003"]
print(df.head())

45
                   0001         0002               0003          0004  \
nombres       Ana Maria  Juan Carlos        Maria Elena     Ana Maria
apellidos  Lopez Garcia   Perez Soto  Rodriguez Mendoza  Lopez Garcia
edad                 34           45                 28            34

                        0005
nombres          Maria Elena
apellidos  Rodriguez Mendoza
edad                      28

In [74]:
df["0003"]["edad"]
df["0004"] =  df["0003"]
df.head()

,0001,0002,0003,0004,0005
nombres,Ana Maria,Juan Carlos,Maria Elena,Maria Elena,Maria Elena
apellidos,Lopez Garcia,Perez Soto,Rodriguez Mendoza,Rodriguez Mendoza,Rodriguez Mendoza
edad,34,45,28,28,28

#### Creando una nueva columna con información de otras columnas

In [75]:
df["0010"] =  df["0003"] +df["0002"]

df.head()

,0001,0002,0003,0004,0005,0010
nombres,Ana Maria,Juan Carlos,Maria Elena,Maria Elena,Maria Elena,Maria ElenaJuan Carlos
apellidos,Lopez Garcia,Perez Soto,Rodriguez Mendoza,Rodriguez Mendoza,Rodriguez Mendoza,Rodriguez MendozaPerez Soto
edad,34,45,28,28,28,73

In [76]:
## Insertar una columna en una posición específica, pero no recomendado
df.insert(1, "1111", df["0003"] )
df.head()

,0001,1111,0002,0003,0004,0005,0010
nombres,Ana Maria,Maria Elena,Juan Carlos,Maria Elena,Maria Elena,Maria Elena,Maria ElenaJuan Carlos
apellidos,Lopez Garcia,Rodriguez Mendoza,Perez Soto,Rodriguez Mendoza,Rodriguez Mendoza,Rodriguez Mendoza,Rodriguez MendozaPerez Soto
edad,34,28,45,28,28,28,73

In [77]:
df = df.assign( nuevo = ["Jose","Rubio",34])

In [78]:
df.head()

,0001,1111,0002,0003,0004,0005,0010,nuevo
nombres,Ana Maria,Maria Elena,Juan Carlos,Maria Elena,Maria Elena,Maria Elena,Maria ElenaJuan Carlos,Jose
apellidos,Lopez Garcia,Rodriguez Mendoza,Perez Soto,Rodriguez Mendoza,Rodriguez Mendoza,Rodriguez Mendoza,Rodriguez MendozaPerez Soto,Rubio
edad,34,28,45,28,28,28,73,34

In [ ]:
df["1111"]["nombres"] = "Jaime"

df.head()

## Series con Pandas

In [ ]:
nro_list = [10,20,40,60,80]
serie_pd = pd.Series(nro_list)
print(serie_pd)

In [ ]:
mi_listado = [x for x in range(2,21,2)]
serie_pares = pd.Series(mi_listado)
print(type(serie_pares))
serie_pares

In [ ]:
mi_listado = range(2,21,2)
serie_pares = pd.Series(mi_listado)
serie_pares

## Convertir ndarray a serie data frame

In [ ]:
nro_list = np.array([10,20,40,60,80])
serie_pd = pd.Series(nro_list)
print(serie_pd)

In [ ]:
mi_listado = np.arange(2,101,2)
serie_pares = pd.Series(mi_listado)
serie_pares

# Estadísticos descriptivos con statsmodels

In [ ]:
import statsmodels.api as sm

a_matrix = np.arange(0,16)
a_matrix  

desc = sm.stats.DescrStatsW(a_matrix)

print(desc.mean)
print(desc.std)
print(desc.var)
print(desc.cov)
print(desc.quantile([0.25,0.5,0.75]))

# Estadísticos descriptivos con scipy

In [ ]:
import scipy.stats as stats

a_matrix = np.arange(0,16)
a_matrix

In [ ]:
print("Minimo:", stats.tmin(a_matrix))
print("Maximo:", stats.tmax(a_matrix))
print("Media:", stats.tmean(a_matrix))
print("Varianza:", stats.tvar(a_matrix))
print("Desviacion Estandar:", stats.tstd(a_matrix)) 
print("Percentil 25:", stats.scoreatpercentile(a_matrix,25))
print("Percentil 50:", stats.scoreatpercentile(a_matrix,50))
print("Percentil 75:", stats.scoreatpercentile(a_matrix,75))
print("Rango intercuartilico:", stats.iqr(a_matrix))
print("Moda:", stats.mode(a_matrix))

# Estadísticos descriptivos para ndarray

In [ ]:
a_matrix = np.arange(0,16).reshape(4,4)
a_matrix

In [ ]:
print("Suma:", a_matrix.sum())
print("Media:", a_matrix.mean())
print("Minimo:", a_matrix.min())
print("Maximo:", a_matrix.max())
print("Varianza:", a_matrix.var())
print("Desviacion Estandar:", a_matrix.std())

In [ ]:
AXIS = 1 # 0 Columna , 1 : Fila
print(a_matrix)
print("Suma:", a_matrix.sum(AXIS))
print("Media:", a_matrix.mean(AXIS))
print("Minimo:", a_matrix.min(AXIS))
print("Maximo:", a_matrix.max(AXIS))
print("Varianza:", a_matrix.var(AXIS))
print("Desviacion Estandar:", a_matrix.std(AXIS))

# Estadísticos descriptivos con numpy

In [ ]:
a_matrix = np.arange(0,16).reshape(4,4)
a_matrix

In [ ]:
print("Sum:", np.sum(a_matrix))
print("Min:", np.min(a_matrix))
print("Max:", np.max(a_matrix))
print("Media:", np.mean(a_matrix))
print("Mediana:", np.median(a_matrix))
print("Moda:", stats.mode(a_matrix))
print("Varianza:", np.var(a_matrix))
print("Desviacion Estandar:", np.std(a_matrix))
print("Percentil 25:", np.percentile(a_matrix,25))
print("Percentil 50:", np.percentile(a_matrix,50))
print("Percentil 75:", np.percentile(a_matrix,75))

In [ ]:
# Estadísticos descriptivos con numpy axis=0 columnas, axis=1 filas
print("Sum:", np.sum(a_matrix, axis=0))
print("Min:", np.min(a_matrix, axis=0))
print("Max:", np.max(a_matrix, axis=0))
print("Media:", np.mean(a_matrix, axis=0))
print("Mediana:", np.median(a_matrix, axis=0))
print("Moda:", stats.mode(a_matrix, axis=0))
print("Varianza:", np.var(a_matrix, axis=0))
print("Desviacion Estandar:", np.std(a_matrix,axis=0))
print("Percentil 25:", np.percentile(a_matrix,25,axis=0))
print("Percentil 50:", np.percentile(a_matrix,50,axis=0))
print("Percentil 75:", np.percentile(a_matrix,75,axis=0))

# Estadísticos descriptivos con Pandas

In [ ]:
ds = pd.Series(np.arange(0,16))
ds

In [ ]:
print("Minimo:", ds.min())
print("Maximo:", ds.max())
print("Media:", ds.mean())
print("Mediana:", ds.median())
print("Moda:", ds.mode()[0])
print("Varianza:", ds.var())        
print("Desviacion Estandar:", ds.std())
print("Percentil 25:", ds.quantile(0.25))
print("Percentil 50:", ds.quantile(0.50))
print("Percentil 75:", ds.quantile(0.75))

## Ejercicios

### Ejercicio 1. Cree una serie de pandas de dos maneras diferentes a partir de la lista: [1, 3, 5, …, 33]. Además, cree una serie pandas de dos maneras diferentes a partir del ndarray: [4, 8, 12, …, 44].

### Ejercicio 2 : Cree una función para calcular la varianza poblacional y otra para calcular la varianza muestral que admita como argumento un ndarray. Aplíquelo al siguiente conjunto de edades: 22, 18, 35, 23, 41, 28, 45, y compare los resultados con los obtenidos mediante los métodos de numpy para calcular la varianza poblacional y muestral.

# Cargar CSV y asignar nombres a columnas

Data set  : https://archive.ics.uci.edu/dataset/53/iris

In [ ]:
import pandas as pd
import numpy as np


data = \
    pd.read_csv("iris.csv", 
        names=["sepal_length", "sepal_width", \
             "petal_length", "petal_width", "class"])
data

In [ ]:
media = data["sepal_length"].mean()

#print(round(media,2))

nro = len(data["sepal_length"]) 
nro

In [ ]:
# Calcular el intervalo de confianza al 95% para la media de la longitud del sépalo.

import scipy.stats as st

nro = len(data["sepal_length"])
media = data["sepal_length"].mean()

# Como tengo mas de 30 muestras uso la distribución normal para calcular el intervalo de confianza
ic = st.norm.interval(confidence = 0.95, loc=media, scale=st.sem(data["sepal_length"]))

print("La media de la longitud del sépalo:", media)
print("Intervalo de confianza al 95% para la media de la longitud del sépalo:", ic)

### Ejercicio 3 : Calcular lo siguiente: mínimo, máximo, media, mediana, moda, varianza poblacional, varianza muestral, desviación estándar poblacional y desviación estándar muestral para el ancho de los petalos del dataset iris.csv

## Correlación

In [ ]:
data

In [ ]:
data.describe()

In [ ]:
data_clone = data.copy()
data_clone.drop(columns=["class"], inplace=True)
corr_matrix = data_clone.corr()
corr_matrix

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns