# Semana 1: Transformación de datos

Link Automobile Dataset: https://www.kaggle.com/datasets/toramky/automobile-dataset

In [2]:
'''
Curso: Análisis de Datos con Python
Sesión 1: Transformación de datos
Fecha: 13/12/2025
Actualización : 23/05/2026
Autor: José Espinoza Melgarejo / Jaime Gómez 
'''

import pandas as pd

filename = "dataset/autos.csv"

headers = ["symboling","normalized-losses","make","fuel-type","aspiration",
           "num-of-doors","body-style","drive-wheels","engine-location","wheel-base",
           "length","width","height","curb-weight","engine-type","num-of-cylinders",
           "engine-size","fuel-system","bore","stroke","compression-ratio","horsepower",
           "peak-rpm","city-mpg","highway-mpg","price"]

df = pd.read_csv(filename, names=headers)
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [3]:
df.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [5]:
df.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

## Descripción de las variables

- 'symboling' : Nivel de riesgo del seguro , de menor riesgo (-3) a mayor riesgto (3)
- "normalized-losses" : Es la perdida del pago promedio del seguro del auto por año y representa la perdida por año del auto. El valor oscila entre 65 a 256
- 'make' : Marca
- "aspiration" : Como el motor de combustión interno trabaja , puede ser estandar (std) o turbo 
- 'num-of-doors' : Número de puertas
- "body-style" : Carroceria
- 'drive-wheels' : Tracción de las ruedas
- 'engine-location' : Localización del motor
- 'wheel-base' : Distancia entre ejes 
- 'length' : Longitud
- 'width' : Ancho
- 'height': Alto
- 'curb-weight' : Peso del auto con equipación completa
- 'engine-type': Tipo de motor
- 'num-of-cylinders' : Número de cilindros
- 'engine-size' : Tamaño del motor
- 'fuel-system' : Sistema de combustible
- 'bore' : Diámetro
- 'stroke' : Distancia recorrida por el pistón durante cada ciclo
- 'compression-ratio': Ratio de comprensión
- 'horsepower' : Caballos de potencia
- 'horsepower-binned' : Caballos de potencia convertidos en una variable categórica 
- 'peak-rpm' : RPM pico 
- 'city-mpg' : consumo en la ciudad en millas por galon
- 'highway-mpg' : consumo en autopista en millas por galon
- 'price' : Precio
- 'city-L/100km' :  consumo en la ciudad en litros por kilometro
- 'diesel' : variable dummy para consumo por petróleo
- 'gas': variable dummy para consumo por gasoina

In [6]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [7]:
df.tail()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [10]:
df[['symboling', 'normalized-losses', 'make']].head()

   symboling normalized-losses         make
0          3                 ?  alfa-romero
1          3                 ?  alfa-romero
2          1                 ?  alfa-romero
3          2               164         audi
4          2               164         audi

In [9]:
df.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [17]:
df.describe().columns

Index(['symboling', 'wheel-base', 'length', 'width', 'height', 'curb-weight',
       'engine-size', 'compression-ratio', 'city-mpg', 'highway-mpg'],
      dtype='object')

In [19]:
df.describe().round(2)

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.00,205.00,205.00,205.00,205.00,205.00,205.00,205.00,205.00,205.00
mean,0.83,98.76,174.05,65.91,53.72,2555.57,126.91,10.14,25.22,30.75
std,1.25,6.02,12.34,2.15,2.44,520.68,41.64,3.97,6.54,6.89
min,-2.00,86.60,141.10,60.30,47.80,1488.00,61.00,7.00,13.00,16.00
25%,0.00,94.50,166.30,64.10,52.00,2145.00,97.00,8.60,19.00,25.00
50%,1.00,97.00,173.20,65.50,54.10,2414.00,120.00,9.00,24.00,30.00
75%,2.00,102.40,183.10,66.90,55.50,2935.00,141.00,9.40,30.00,34.00
max,3.00,120.90,208.10,72.30,59.80,4066.00,326.00,23.00,49.00,54.00

In [22]:
df["engine-size"].describe().round(2)

count    205.00
mean     126.91
std       41.64
min       61.00
25%       97.00
50%      120.00
75%      141.00
max      326.00
Name: engine-size, dtype: float64

In [23]:
# Una vista de la data
dfx = df[["symboling","normalized-losses","make","fuel-type","price"]]
dfx.head()

   symboling normalized-losses         make fuel-type  price
0          3                 ?  alfa-romero       gas  13495
1          3                 ?  alfa-romero       gas  16500
2          1                 ?  alfa-romero       gas  16500
3          2               164         audi       gas  13950
4          2               164         audi       gas  17450

In [ ]:
# Una copia de la data
dfx_new = dfx.copy()
dfx_new.head()

   symboling normalized-losses         make fuel-type  price
0          3                 ?  alfa-romero       gas  13495
1          3                 ?  alfa-romero       gas  16500
2          1                 ?  alfa-romero       gas  16500
3          2               164         audi       gas  13950
4          2               164         audi       gas  17450

In [ ]:
# Solo mostrar la data
dfx

     symboling normalized-losses         make fuel-type  price
0            3                 ?  alfa-romero       gas  13495
1            3                 ?  alfa-romero       gas  16500
2            1                 ?  alfa-romero       gas  16500
3            2               164         audi       gas  13950
4            2               164         audi       gas  17450
..         ...               ...          ...       ...    ...
200         -1                95        volvo       gas  16845
201         -1                95        volvo       gas  19045
202         -1                95        volvo       gas  21485
203         -1                95        volvo    diesel  22470
204         -1                95        volvo       gas  22625

[205 rows x 5 columns]

## Procedimiento para gestionar datos perdidos

### Identificar datos perdidos

In [ ]:
key_data_missing = "?"
DATA_MISSING = "?"

# Datos válidos del precio de los autos
nro_price_validate = df['price'].loc[df['price'] != DATA_MISSING].count()
print(nro_price_validate)

201

In [38]:
# Datos perdidos del precio de los autos
nro_price_missing = df['price'].loc[df['price'] == DATA_MISSING].count()
print(nro_price_missing)

# print(len(df))

4

In [39]:
nro_price_reg = df['price'].count()
nro_price_reg

np.int64(205)

In [36]:
df["price"].describe()

count     205
unique    187
top         ?
freq        4
Name: price, dtype: object

In [37]:
df.count()

symboling            205
normalized-losses    205
make                 205
fuel-type            205
aspiration           205
num-of-doors         205
body-style           205
drive-wheels         205
engine-location      205
wheel-base           205
length               205
width                205
height               205
curb-weight          205
engine-type          205
num-of-cylinders     205
engine-size          205
fuel-system          205
bore                 205
stroke               205
compression-ratio    205
horsepower           205
peak-rpm             205
city-mpg             205
highway-mpg          205
price                205
dtype: int64

## Porcentaje de datos perdidos

In [40]:
nro_price_validate = df['price'].loc[df['price'] != DATA_MISSING].count()
print(nro_price_validate)

print("-----------------------------------------------------------")
nro_price_missing = df['price'].loc[df['price'] == DATA_MISSING].count()
print(nro_price_missing)

print("-----------------------------------------------------------")
print("Porcentaje de válidos =", nro_price_missing/nro_price_validate*100,"%")

201
-----------------------------------------------------------
4
-----------------------------------------------------------
Porcentaje de válidos = 1.9900497512437811 %

In [42]:
# ¿Podemos decir que la variable width tiene datos perdidos?
nro_width_validate = df['width'].loc[df['width'] != DATA_MISSING].count()

print(nro_width_validate)

205

## Representando valores nulos y descargando data

In [43]:
import numpy as np
# Representación de un dato faltante
print("Valor nulo =",np.nan)

Valor nulo = nan

In [51]:
# Reemplazar "?" a valor nulo (np.nan)
df.replace(DATA_MISSING, np.nan, inplace=True)
df.head(10)

# TO DO : Se debe reemplazar todos los datos incompletos que se considerar nulos con np.nan

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,NaN

In [46]:
# Descargar datos tratadps en formato CSV
df.to_csv("output/data_tratada.csv")

## Identificando variables con datos perdidos

In [48]:
# Variables con datos perdidos
missing_data = df.isnull()
missing_data.head(10)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [55]:
missing_data['normalized-losses'].head(10)

0     True
1     True
2     True
3    False
4    False
5     True
6    False
7     True
8    False
9     True
Name: normalized-losses, dtype: bool

In [56]:
md = missing_data['normalized-losses'].value_counts()
md

normalized-losses
False    164
True      41
Name: count, dtype: int64

In [ ]:
# Cantidad de tipos de valores que tiene el campo "normalized-losses"
nro_tipos = len(missing_data['normalized-losses'].value_counts())
print(f" La variable 'normalized-losses' tiene {nro_tipos} tipos de datos")

 La variable 'normalized-losses' tiene 2  tipos de datos

In [59]:
# ¿Cuanto tipos de combustible existe de acuerdo a la variable fuel-type?
df['fuel-type'].value_counts()

fuel-type
gas       185
diesel     20
Name: count, dtype: int64

In [60]:
# ¿Cuanto tipos de motor existe de acuerdo a la variable engine-type?
df['engine-type'].value_counts()

engine-type
ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: count, dtype: int64

In [61]:
# Contar datos perdidos por columnas.  
for column in list(missing_data.columns):
    if len(missing_data[column].value_counts()) > 1:
        print(f"Variable = {column}")             # nueva
        print(missing_data[column].value_counts())
        print("")

Variable = normalized-losses
normalized-losses
False    164
True      41
Name: count, dtype: int64

Variable = num-of-doors
num-of-doors
False    203
True       2
Name: count, dtype: int64

Variable = bore
bore
False    201
True       4
Name: count, dtype: int64

Variable = stroke
stroke
False    201
True       4
Name: count, dtype: int64

Variable = horsepower
horsepower
False    203
True       2
Name: count, dtype: int64

Variable = peak-rpm
peak-rpm
False    203
True       2
Name: count, dtype: int64

Variable = price
price
False    201
True       4
Name: count, dtype: int64

In [62]:
# Contar datos perdidos por columnas
for column in list(missing_data.columns):
     if len(missing_data[column].value_counts()) == 2:
        print(f"Variable = {column}")
        print(missing_data[column].value_counts())
        print("")

Variable = normalized-losses
normalized-losses
False    164
True      41
Name: count, dtype: int64

Variable = num-of-doors
num-of-doors
False    203
True       2
Name: count, dtype: int64

Variable = bore
bore
False    201
True       4
Name: count, dtype: int64

Variable = stroke
stroke
False    201
True       4
Name: count, dtype: int64

Variable = horsepower
horsepower
False    203
True       2
Name: count, dtype: int64

Variable = peak-rpm
peak-rpm
False    203
True       2
Name: count, dtype: int64

Variable = price
price
False    201
True       4
Name: count, dtype: int64

## Contando datos perdidos por columnas

In [ ]:
nro_reg = len(df)

#for column in missing_data.columns.values.tolist():
for column in list(missing_data.columns):
    s = missing_data[column].value_counts()
    #print(s)
    if s.iloc[0] != nro_reg: 
       print(f"La variable {column} tiene {s.iloc[0]} datos completos y {s.iloc[1]} datos faltantes")

La variable normalized-losses tiene 164 datos completos y 41 perdidos
La variable num-of-doors tiene 203 datos completos y 2 perdidos
La variable bore tiene 201 datos completos y 4 perdidos
La variable stroke tiene 201 datos completos y 4 perdidos
La variable horsepower tiene 203 datos completos y 2 perdidos
La variable peak-rpm tiene 203 datos completos y 2 perdidos
La variable price tiene 201 datos completos y 4 perdidos

In [ ]:
nro_reg = len(df)

for column in missing_data.columns.values.tolist():
    s = missing_data[column].value_counts()
    # print(s)
    # print(type(s))
    if s.iloc[0] != nro_reg:
       print("La variable", column, "tiene", s.iloc[0] ,"datos completos")
       print("")

In [ ]:
# Otra alternativa
p = (missing_data.sum()/len(missing_data)*100).sort_values(ascending=False)
p

## Tratamiento de datos faltantes

In [ ]:
# Mostrar tipos de datos asignados al momento de cargar el DataFrame
df.dtypes

In [ ]:
'''# No se puede ejecutar directamente porque los datos son cadena
df['price'].mean()'''

In [ ]:
## Convertir la variable price a tipo float
# Paso 1: Convertir la variable price a tipo float astype('float')
# Paso 2: Calcular el promedio de la variable price
df['price'].astype('float').mean()

In [ ]:
# Imputación para la variable bore
avg_bore = df['bore'].astype('float').mean()
avg_bore = round(avg_bore,4)      
print(f"El promedio de la variable bore es {avg_bore} ")
#df["bore"].replace(np.nan, avg_bore, inplace=True)
df["bore"] = df["bore"].replace(np.nan, avg_bore)

In [ ]:
# Imputación para la variable normalized-losses
avg_norm_loss = df["normalized-losses"].astype("float").mean()
avg_norm_loss = round(avg_norm_loss,4)    
print("El promedio de normalized-losses es", avg_norm_loss)

# df["normalized-losses"].replace(np.nan, avg_norm_loss, inplace=True)
# Usar fillna en lugar de replace
df["normalized-losses"] = df["normalized-losses"].fillna(avg_norm_loss)

In [ ]:
# Imputación para la variable horsepower
avg_horsepower=df['horsepower'].astype('float').mean()
avg_horsepower = round(avg_horsepower,4)
print("El promedio de la variable horsepower es", avg_horsepower)
# df["horsepower"].replace(np.nan, avg_horsepower, inplace=True)
df["horsepower"] = df["horsepower"].fillna(avg_horsepower)

In [ ]:
# Imputación para la variable peak-rpm
avg_peak_rpm=df['peak-rpm'].astype('float').mean()
avg_peak_rpm = round(avg_peak_rpm,4)
print("El promedio de la variable peak-rpm es", avg_peak_rpm)
#df["peak-rpm"].replace(np.nan, avg_peak_rpm, inplace=True)
df["peak-rpm"] = df["peak-rpm"].fillna(avg_peak_rpm)

In [ ]:
# Promedio para un grupo de variables
lista = ["normalized-losses","stroke","horsepower","peak-rpm"]
for column in lista:
    avg = df[column].astype('float').mean(axis=0)
    avg = round(avg,4)
    #df[column].replace(np.nan, avg, inplace=True)
    df[column] = df[column].fillna(avg)
    print(f"El promedio de la variable {column} es {avg}")

In [ ]:
# Imputación de las variables stroke, peak-rpm, horsepower y normalized-losses
for i in ["stroke","peak-rpm","horsepower","normalized-losses"]:
    avg = df[i].astype("float").mean()
    #df[i].replace(np.nan, avg, inplace=True)
    df[i] = df[i].fillna(avg)

    
df[["stroke","peak-rpm","horsepower","normalized-losses"]]

In [ ]:
# Variables con datos perdidos
missing_data = df.isnull()
missing_data

In [ ]:
# Porcentaje de valores perdidos (primera forma)
(missing_data.sum()/len(missing_data)*100).sort_values(ascending=False)

In [ ]:
# Porcentaje de valores perdidos (segunda forma)
nro_reg = len(df)

for column in missing_data.columns.values.tolist():
    s = missing_data[column].value_counts()
    if s.iloc[0] != nro_reg:
       print("La variable", column, "tiene", s.iloc[0] ,"datos completos")
       percentaje_missing_data = ((nro_reg - s.iloc[0])/nro_reg)*100
       print(round(percentaje_missing_data,0),"%")

### Imputación por la moda

In [ ]:
# Buscando la moda
print("Frecuencias por categoría: \n",df["num-of-doors"].value_counts())

# Otra manera de visualizar la moda
print("-----------------------------------------------------------")
mode = df['num-of-doors'].value_counts().idxmax()
print("Moda =",mode)

# Se reemplaza con la moda
print("-----------------------------------------------------------")
#df["num-of-doors"].replace(np.nan, mode, inplace=True)
df["num-of-doors"] = df["num-of-doors"].fillna(mode)


# Se obtiene las variables con datos perdidos
missing_data = df.isnull()
(missing_data.sum()/len(missing_data)*100).sort_values(ascending=False)

In [ ]:
# Eliminando las filas que tengan datos faltantes en la variable price
row = 0
df.dropna(subset=["price"], axis=row, inplace=True)

# Reseteando el índice porque se han borrado 4 líneas
df.reset_index(drop=True, inplace=True)

len(df)

In [ ]:
# Contar los valores nulos por variable
missing_data = df.isnull()
print(missing_data.sum())

# Descargar datos en formato CSV
df.to_csv("output/data2.csv")

# Almacenar datos descargados en un data frame
print("-----------------------------------------------------------")
dfx = pd.read_csv("output/data2.csv")
print(dfx)

### Corrección de formato de datos

In [ ]:
# Observar tipo de datos por variable
df.dtypes

In [ ]:
# Cambiar tipo de dato para una variable
print("-----------------------------------------------------------")
df["price"] = df["price"].astype("float")
df.dtypes

In [ ]:
# Cambiar formato para un grupo de variables
df["bore"] = df["bore"].astype("float")
df["peak-rpm"] = df["peak-rpm"].astype("float")
df["stroke"] = df["stroke"].astype("float")
df["normalized-losses"] = df["normalized-losses"].astype("int")

In [ ]:
# Automatizondo las conversiones
variables = ["bore", "stroke", "peak-rpm"]
for i in variables:
    df[i] = df[i].astype("float")
df["normalized-losses"] = df["normalized-losses"].astype("int")
df.dtypes

## Formateando datos

In [ ]:
import random

# Definir el rango de fechas
inicio = pd.to_datetime('2025-01-01 00:00:00')
fin = pd.to_datetime('2025-12-31 23:59:59')

# Función para generar una fecha y hora aleatoria dentro del rango
def fecha_hora_aleatoria(inicio, fin):
    delta = fin - inicio
    int_delta = int(delta.total_seconds())
    aleatorio_segundos = random.randint(0, int_delta)
    return inicio + pd.to_timedelta(aleatorio_segundos, unit='s')

# Generar la columna de fechas y horas aleatorias
df['date_time'] = [fecha_hora_aleatoria(inicio, fin) for _ in range(len(df))]
df.head()

In [ ]:
import datetime
df["date_time_new1"] = df["date_time"].apply(lambda x: x.strftime("%d-%m-%Y %H:%M:%S"))

df["date_time_new2"] = df["date_time"].apply(lambda x: x.strftime("%d-%m-%y %H:%M:%S"))

df["date_time_new3"] = df["date_time"].apply(lambda x: x.strftime("%m-%Y %H:%M:%S"))

df.head()

In [ ]:
df["day"] = df["date_time"].dt.day
df["day_week"] = df["date_time"].dt.day_name()
df["month"] = df["date_time"].dt.month
df["year"] = df["date_time"].dt.year
df["time"] = df["date_time"].dt.time
df.head()

### Normalización de datos

In [ ]:
# Obtenemos el mayor valor
max1 = df['length'].max()

# Obtenemos el menor valor
min1 = df['length'].min()

# Mostramos los datos
print("-----------------------------------------------------------")
print(df[['length']].head())

print("-----------------------------------------------------------")
# Reemplazamos (valor original - mínimo)/(máximo - mínimo)
df['length_norm1'] = (df['length'] - min1)/(max1 - min1)
df[['length_norm1']].head()

In [ ]:
# Obtenemos el mayor valor
max2 = df['width'].max()

# Obtenemos el menor valor
min2 = df['width'].min()

# Mostramos los datos
print("-----------------------------------------------------------")
print(df[['width']].head())

print("-----------------------------------------------------------")
# Reemplazamos (valor original - mínimo)/(máximo - mínimo)
df['width_norm1'] = (df['width']- min2)/(max2 - min2)
print(df[['width_norm1']].head())

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
A = scaler.fit_transform(df[["length"]])
B = scaler.fit_transform(df[["width"]])
df["length_norm2"] = pd.DataFrame(data=A)
df["width_norm2"] = pd.DataFrame(data=B)
print(df[['length_norm2','width_norm2']].head())

In [ ]:
# Convirtiendo mpg a km (0.4251 multiplicado por mpg)
print("-----------------------------------------------------------")
df['city-km'] = round(df["city-mpg"]*0.4251,3)
print(df[['city-mpg','city-km']].head())

print("-----------------------------------------------------------")
df['highway-km'] = round(df["highway-mpg"]*0.4251,3)
print(df[['highway-mpg','highway-km']].head())

print("-----------------------------------------------------------")
df.columns

## Variables numéricas y categóricas

### Estandarización de datos

In [ ]:
# Obtenemos la media
mean1 = df['length'].mean()
mean2 = df['width'].mean()

# Obtenemos la desviación estándar poblacional (ddof=0)
std1 = df['length'].std(ddof=0)
std2 = df['width'].std(ddof=0)

# Mostramos los datos
print("-----------------------------------------------------------")
print(df[['length','width']].head())

# Reemplazamos (valor original - media)/(desviación estándar)
df['length_std1'] = (df['length'] - mean1)/std1
df['width_std1'] = (df['width'] - mean2)/std2
print(df[['length_std1', 'width_std1']])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
A = scaler.fit_transform(df[["length"]])
B = scaler.fit_transform(df[["width"]])
df["length_std2"] = pd.DataFrame(data=A)
df["width_std2"] = pd.DataFrame(data=B)
print(df[['length_std2','width_std2']])

## Particionamiento mediante un histograma

In [ ]:
# Ver tipo de variable
df[["horsepower"]].dtypes

In [ ]:
# Se convierte a enteros
df["horsepower"] = df["horsepower"].astype(int)
df[["horsepower"]].dtypes

In [ ]:
# Graficando histograma para horsepower
import matplotlib.pyplot as plt

plt.hist(df["horsepower"]) # El valor por defecto bins = 10
plt.xlabel("horsepower")
plt.ylabel("Número de veces")
plt.title("horsepower bins")

In [ ]:
# Generar puntos de corte 
minimo = df["horsepower"].min()
maximo = df["horsepower"].max()
punto_de_corte = 4
bins = np.linspace(minimo,maximo,punto_de_corte)
print("Particiones =",bins)

print("-----------------------------------------------------------")
bins_custom = [48, 100, 200, 262] # cortes personalizados
group_names = ['Bajo', 'Medio', 'Alto']

df['horsepower-binned'] = pd.cut(df['horsepower'], bins, labels=group_names)
df['horsepower-binned-custom'] = pd.cut(df['horsepower'], bins_custom, labels=group_names)
df[['horsepower','horsepower-binned','horsepower-binned-custom']].head()

In [ ]:
df["horsepower-binned"].value_counts()

In [ ]:
df["horsepower-binned-custom"].value_counts()

In [ ]:
plt.bar(group_names, df["horsepower-binned"].value_counts())
plt.xlabel("horsepower")
plt.ylabel("Número de veces")
plt.title("horsepower bins")

In [ ]:
plt.hist(df["horsepower"], bins = 3)
plt.xlabel("horsepower")
plt.ylabel("Número de veces")
plt.title("horsepower bins")

### Variables dummy

In [ ]:
df[["fuel-type"]].dtypes

In [ ]:
df["fuel-type"].head()

In [ ]:
df["fuel-type"].value_counts()

In [ ]:
dummy_variable_1 = pd.get_dummies(df["fuel-type"])
dummy_variable_1.head()

In [ ]:
print("-----------------------------------------------------------")
dummy_variable_1.rename(columns={'gas':'fuel-type-gas', 'diesel':'fuel-type-diesel'}, 
                        inplace=True)
dummy_variable_1.head()

In [ ]:
df = pd.concat([df, dummy_variable_1], axis=1)
df.drop("fuel-type", axis = 1, inplace=True)
df.head()

In [ ]:
dummy_variable_2 = pd.get_dummies(df["aspiration"])
dummy_variable_2.rename(columns={'std':'aspiration-type-standar', 'turbo':'aspiration-type-turbo'}, 
                        inplace=True)
df = pd.concat([df, dummy_variable_2], axis=1)
df[["aspiration","aspiration-type-standar","aspiration-type-turbo"]].tail(10)

In [ ]:
df = pd.concat([df, dummy_variable_2], axis=1)
df.drop("aspiration", axis = 1, inplace=True)
df

In [ ]:
df.to_csv('output/autos_data_limpia.csv')